package com.opssino.sms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTSmsLogs<M extends BaseTSmsLogs<M>> extends Model<M> implements IBean {

	public void setIDS(java.lang.Long IDS) {
		set("IDS", IDS);
	}

	public java.lang.Long getIDS() {
		return get("IDS");
	}

	public void setSmsType(java.lang.Long smsType) {
		set("SMS_TYPE", smsType);
	}

	public java.lang.Long getSmsType() {
		return get("SMS_TYPE");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("PHONE_NUMBER", phoneNumber);
	}

	public java.lang.String getPhoneNumber() {
		return get("PHONE_NUMBER");
	}

	public void setMESSAGE(java.lang.String MESSAGE) {
		set("MESSAGE", MESSAGE);
	}

	public java.lang.String getMESSAGE() {
		return get("MESSAGE");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("SEND_TIME", sendTime);
	}

	public java.util.Date getSendTime() {
		return get("SEND_TIME");
	}

	public void setIsOk(java.lang.Long isOk) {
		set("IS_OK", isOk);
	}

	public java.lang.Long getIsOk() {
		return get("IS_OK");
	}

	public void setFailReason(java.lang.String failReason) {
		set("FAIL_REASON", failReason);
	}

	public java.lang.String getFailReason() {
		return get("FAIL_REASON");
	}

	public void setClentBody(java.lang.String clentBody) {
		set("CLENT_BODY", clentBody);
	}

	public java.lang.String getClentBody() {
		return get("CLENT_BODY");
	}

	public void setReSendCount(java.lang.Integer reSendCount) {
		set("re_send_count", reSendCount);
	}

	public java.lang.Integer getReSendCount() {
		return get("re_send_count")==null?0:Integer.parseInt(get("re_send_count").toString());
	}

	public void setReFlag(java.lang.Integer reFlag) {
		set("re_flag", reFlag);
	}

	public java.lang.Integer getReFlag() {
		return get("re_flag");
	}

	public void setLastSendTime(java.util.Date lastSendTime) {
		set("last_send_time", lastSendTime);
	}

	public java.util.Date getLastSendTime() {
		return get("last_send_time");
	}

}
