package com.opssino.sms.common.model;

import java.util.List;

import org.smslib.OutboundMessage;

import com.jfinal.kit.JMap;
import com.jfinal.plugin.activerecord.Page;
import com.opssino.sms.common.model.base.BaseTSmsLogs;
import com.opssino.sms.util.SmsMain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TSmsLogs extends BaseTSmsLogs<TSmsLogs> {
	public static final TSmsLogs dao = new TSmsLogs();
	public Page<TSmsLogs> paginate(int pageNumber, int pageSize,String where,Object...parms) {
		return paginate(pageNumber, pageSize, "select *", where,parms);
	}
	
	public List<TSmsLogs> getErrorMessage(int lastHouse){
		return dao.find(getSql("findErrorMessage"),lastHouse);
	}
	
}
